#!/bin/bash
# Zip each sub-directory into its own zip file.
# TODO: chech parallel is installed.
# TODO: chech zip is installed.
# TODO: write help.

parallel zip -r {.}.zip {} ::: $(find . -maxdepth 1 -type d)

